%indseqcondcell = cell(size(id,2),nconds,nconds); will be generated by NM2AllConditions
% this program calls  AnovaIndAnalysis to draw graphs for different
% configuration and stored them in specific subfolders, 

%NM2AllConditions; % load all data

Outdir = uigetdir('D:\Arian\Projects\SMART\Outputs\mintAtBHypoth\Individual\TripleSequenceAnova\','Select Output Upper Directory for the Graphs!'); 

%@@@@@@@@@@@@@@@@@@@@@  A 4status      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  A 4status      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'A-A-A','V-A-A','A-V-A','V-V-A'};
listcond=[[7;7] [5;7] [10;5] [8;5]];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\A_4states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END A 4 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

%@@@@@@@@@@@@@@@@@@@@@  V 4 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  V 4 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'V-V-V','A-V-V','V-A-V','A-A-V'};
listcond=[[8;8] [10;8] [5;10] [7;10]];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\V_4states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END V 4 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

%@@@@@@@@@@@@@@@@@@@@@  A 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  A 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'A.-A.-A.','AV-A.-A.','V.-A.-A.','A.-AV-A.','A.-V.-A.','AV-AV-A.','V.-AV-A.','AV-V.-A.','V.-V.-A.'}; % dot is required to make all states same length
listcond=[[7;7] [6;7] [5;7] [13;6] [10;5] [12;6] [11;6] [9;5] [8;5]];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\A_9states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END A 9 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

%@@@@@@@@@@@@@@@@@@@@@  V 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  V 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'V.-V.-V.','AV-V.-V.','A.-V.-V.','V.-AV-V.','V.-A.-V.','AV-AV-V.','A.-AV-V.','AV-A.-V.','A.-A.-V.'};
listcond=[   [8;8]    [9;8]   [10;8]  [11;9]   [5;10]    [12;9]   [13;9]   [6;10]   [7;10] ];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\V_9states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END V 9 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

%@@@@@@@@@@@@@@@@@@@@@  AV 9 states     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  AV 9 states     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'AV-AV-AV','A.-AV-AV','V.-AV-AV','AV-A.-AV','AV-V.-AV','A.-A.-AV','V.-A.-AV','A.-V.-AV','V.-V.-AV'};
listcond=[   [12;12]     [13;12]   [11;12]  [6;13]    [9;11]    [7;13]   [5;13]  [10;11]  [8;11] ];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\AV_9states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END AV 9 states @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


%@@@@@@@@@@@@@@@@@@@@@  A 2status switch-nonswicth     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  A 2status switch-nonswicth     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'A-A','A-A','V-A','V-A'};
listcond=[[7;7] [5;7] [10;5] [8;5]];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\A_2states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END A 4 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

%@@@@@@@@@@@@@@@@@@@@@  V 2 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  V 2 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'V-V','V-V','A-V','A-V'};
listcond=[[8;8] [10;8] [5;10] [7;10]];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\V_2states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END V 2 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


%@@@@@@@@@@@@@@@@@@@@@  A Strong Weak Swiches       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  A Strong Weak Swiches       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@  AV-V-A + V-V-A                        Strong--Switch
%@@@@@@@@  A-V-A                                 Weak----Switch
%@@@@@@@@  V-A-A                                 Weaker--Switch
%@@@@@@@@  V-AV-A+AV-AV-A+A-AV-A+AV-A-A+A-A-A    Weakest-Switch
close all;
invarlist ={'Weakest-Switch','Weakest-Switch','Weaker--Switch','Weakest-Switch','Weak----Switch','Weakest-Switch','Weakest-Switch','Strong--Switch','Strong--Switch'}; % dot is required to make all states same length
listcond=[[7;7] [6;7] [5;7] [13;6] [10;5] [12;6] [11;6] [9;5] [8;5]];
alphath=0.05;

[pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\A_StrongWeak\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END A Strong Weak Swiches   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@




