% indseqcondcell = cell(size(id,2),nconds,nconds); will be generated by NM2AllConditions
% this program calls  AnovaIndAnalysis to draw graphs for different
% configuration and stored them in specific subfolders, 

%NM2AllConditions; % load all data

Outdir = uigetdir('D:\Arian\Projects\SMART\Outputs\mintAtBHypoth\Individual\TripleSequenceAnova\','Select Output Upper Directory for the Graphs!'); 


% %@@@@@@@@@@@@@@@@@@@@@  A 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
% %@@@@@@@@@@@@@@@@@@@@@  A 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
% close all;
% invarlist ={'A.-A.-A.','AV-A.-A.','V.-A.-A.','A.-AV-A.','A.-V.-A.','AV-AV-A.','V.-AV-A.','AV-V.-A.','V.-V.-A.'}; % dot is required to make all states same length
% listcond=[[7;7] [6;7] [5;7] [13;6] [10;5] [12;6] [11;6] [9;5] [8;5]];
% alphath=0.05;
% 
% [pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\A_9states\'),alphath,indseqcondcell,id,invarlist,listcond);
% %@@@@@@@@@@@@@@@@@@@@@  END A 9 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
% 
% %@@@@@@@@@@@@@@@@@@@@@  V 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
% %@@@@@@@@@@@@@@@@@@@@@  V 9 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
% close all;
% invarlist ={'V.-V.-V.','AV-V.-V.','A.-V.-V.','V.-AV-V.','V.-A.-V.','AV-AV-V.','A.-AV-V.','AV-A.-V.','A.-A.-V.'};
% listcond=[   [8;8]    [9;8]   [10;8]  [11;9]   [5;10]    [12;9]   [13;9]   [6;10]   [7;10] ];
% alphath=0.05;
% 
% [pindv,statsindv,meansindv,resultsindv] = AnovaIndAnalysis(strcat(Outdir,'\V_9states\'),alphath,indseqcondcell,id,invarlist,listcond);
% %@@@@@@@@@@@@@@@@@@@@@  END V 9 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


%@@@@@@@@@@@@@@@@@@@@@  A 2status switch-nonswicth     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  A 2status switch-nonswicth     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'A-A','A-A','V-A','V-A'};
listcond=[[7;7] [5;7] [10;5] [8;5]];
alphath=0.05;

[halfwidthindvI,pindvI,statsindvI,tblindvI,meansindvI,resultsindvI,critindvI,seindvI,pvalindvI] = AnovaIndAnalysisVecOut(strcat(Outdir,'\A_2states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END A 4 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

%@@@@@@@@@@@@@@@@@@@@@  V 2 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
%@@@@@@@@@@@@@@@@@@@@@  V 2 states      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
close all;
invarlist ={'V-V','V-V','A-V','A-V'};
listcond=[[8;8] [10;8] [5;10] [7;10]];
alphath=0.05;

[halfwidthindvII,pindvII,statsindvII,tblindvII,meansindvII,resultsindvII,critindvII,seindvII,pvalindvII] = AnovaIndAnalysisVecOut(strcat(Outdir,'\V_2states\'),alphath,indseqcondcell,id,invarlist,listcond);
%@@@@@@@@@@@@@@@@@@@@@  END V 2 states  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

pindvII{40}
statsindvII{40}
tblindvII{40}
meansindvII{40}
resultsindvII{40}
critindvII{40}
seindvII{40}
pvalindvII{40}
halfwidthindvII{40}

